/****************************************************************************
 *
 *   Copyright (C) 2013-2016 PX4 Development Team. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name PX4 nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/

/* Auto-generated by genmsg_cpp from file mavlink_msg.msg */


#include <inttypes.h>
#include <px4_platform_common/log.h>
#include <px4_platform_common/defines.h>
#include <uORB/topics/mavlink_msg.h>
#include <uORB/topics/uORBTopics.hpp>
#include <drivers/drv_hrt.h>
#include <lib/drivers/device/Device.hpp>
#include <lib/matrix/matrix/math.hpp>
#include <lib/mathlib/mathlib.h>

constexpr char __orb_mavlink_msg_fields[] = "uint64_t timestamp;uint16_t msg_len;uint8_t[280] msg;uint8_t[6] _padding0;";

ORB_DEFINE(mavlink_msg, struct mavlink_msg_s, 290, __orb_mavlink_msg_fields, static_cast<uint8_t>(ORB_ID::mavlink_msg));
ORB_DEFINE(mavlink_rx_msg, struct mavlink_msg_s, 290, __orb_mavlink_msg_fields, static_cast<uint8_t>(ORB_ID::mavlink_rx_msg));
ORB_DEFINE(mavlink_tx_msg, struct mavlink_msg_s, 290, __orb_mavlink_msg_fields, static_cast<uint8_t>(ORB_ID::mavlink_tx_msg));


void print_message(const mavlink_msg_s &message)
{

	PX4_INFO_RAW(" mavlink_msg_s\n");

	const hrt_abstime now = hrt_absolute_time();

	if (message.timestamp != 0) {
		PX4_INFO_RAW("\ttimestamp: %" PRIu64 "  (%.6f seconds ago)\n", message.timestamp, (now - message.timestamp) / 1e6);
	} else {
		PX4_INFO_RAW("\n");
	}
	PX4_INFO_RAW("\tmsg_len: %u\n", message.msg_len);
	PX4_INFO_RAW("\tmsg: [%u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u]\n", message.msg[0], message.msg[1], message.msg[2], message.msg[3], message.msg[4], message.msg[5], message.msg[6], message.msg[7], message.msg[8], message.msg[9], message.msg[10], message.msg[11], message.msg[12], message.msg[13], message.msg[14], message.msg[15], message.msg[16], message.msg[17], message.msg[18], message.msg[19], message.msg[20], message.msg[21], message.msg[22], message.msg[23], message.msg[24], message.msg[25], message.msg[26], message.msg[27], message.msg[28], message.msg[29], message.msg[30], message.msg[31], message.msg[32], message.msg[33], message.msg[34], message.msg[35], message.msg[36], message.msg[37], message.msg[38], message.msg[39], message.msg[40], message.msg[41], message.msg[42], message.msg[43], message.msg[44], message.msg[45], message.msg[46], message.msg[47], message.msg[48], message.msg[49], message.msg[50], message.msg[51], message.msg[52], message.msg[53], message.msg[54], message.msg[55], message.msg[56], message.msg[57], message.msg[58], message.msg[59], message.msg[60], message.msg[61], message.msg[62], message.msg[63], message.msg[64], message.msg[65], message.msg[66], message.msg[67], message.msg[68], message.msg[69], message.msg[70], message.msg[71], message.msg[72], message.msg[73], message.msg[74], message.msg[75], message.msg[76], message.msg[77], message.msg[78], message.msg[79], message.msg[80], message.msg[81], message.msg[82], message.msg[83], message.msg[84], message.msg[85], message.msg[86], message.msg[87], message.msg[88], message.msg[89], message.msg[90], message.msg[91], message.msg[92], message.msg[93], message.msg[94], message.msg[95], message.msg[96], message.msg[97], message.msg[98], message.msg[99], message.msg[100], message.msg[101], message.msg[102], message.msg[103], message.msg[104], message.msg[105], message.msg[106], message.msg[107], message.msg[108], message.msg[109], message.msg[110], message.msg[111], message.msg[112], message.msg[113], message.msg[114], message.msg[115], message.msg[116], message.msg[117], message.msg[118], message.msg[119], message.msg[120], message.msg[121], message.msg[122], message.msg[123], message.msg[124], message.msg[125], message.msg[126], message.msg[127], message.msg[128], message.msg[129], message.msg[130], message.msg[131], message.msg[132], message.msg[133], message.msg[134], message.msg[135], message.msg[136], message.msg[137], message.msg[138], message.msg[139], message.msg[140], message.msg[141], message.msg[142], message.msg[143], message.msg[144], message.msg[145], message.msg[146], message.msg[147], message.msg[148], message.msg[149], message.msg[150], message.msg[151], message.msg[152], message.msg[153], message.msg[154], message.msg[155], message.msg[156], message.msg[157], message.msg[158], message.msg[159], message.msg[160], message.msg[161], message.msg[162], message.msg[163], message.msg[164], message.msg[165], message.msg[166], message.msg[167], message.msg[168], message.msg[169], message.msg[170], message.msg[171], message.msg[172], message.msg[173], message.msg[174], message.msg[175], message.msg[176], message.msg[177], message.msg[178], message.msg[179], message.msg[180], message.msg[181], message.msg[182], message.msg[183], message.msg[184], message.msg[185], message.msg[186], message.msg[187], message.msg[188], message.msg[189], message.msg[190], message.msg[191], message.msg[192], message.msg[193], message.msg[194], message.msg[195], message.msg[196], message.msg[197], message.msg[198], message.msg[199], message.msg[200], message.msg[201], message.msg[202], message.msg[203], message.msg[204], message.msg[205], message.msg[206], message.msg[207], message.msg[208], message.msg[209], message.msg[210], message.msg[211], message.msg[212], message.msg[213], message.msg[214], message.msg[215], message.msg[216], message.msg[217], message.msg[218], message.msg[219], message.msg[220], message.msg[221], message.msg[222], message.msg[223], message.msg[224], message.msg[225], message.msg[226], message.msg[227], message.msg[228], message.msg[229], message.msg[230], message.msg[231], message.msg[232], message.msg[233], message.msg[234], message.msg[235], message.msg[236], message.msg[237], message.msg[238], message.msg[239], message.msg[240], message.msg[241], message.msg[242], message.msg[243], message.msg[244], message.msg[245], message.msg[246], message.msg[247], message.msg[248], message.msg[249], message.msg[250], message.msg[251], message.msg[252], message.msg[253], message.msg[254], message.msg[255], message.msg[256], message.msg[257], message.msg[258], message.msg[259], message.msg[260], message.msg[261], message.msg[262], message.msg[263], message.msg[264], message.msg[265], message.msg[266], message.msg[267], message.msg[268], message.msg[269], message.msg[270], message.msg[271], message.msg[272], message.msg[273], message.msg[274], message.msg[275], message.msg[276], message.msg[277], message.msg[278], message.msg[279]);
	
}
